
INSERT INTO genders
(name, description, gender_group, gender_type, usage_popularity)
VALUES
('Female', 'Female (Cisgender)', 1, 1, -1),
('Male', 'Male (Cisgender)', 2, 1, -1),
('Intersex', '', 3, 3, -1),
('Trans*', '', NULL, 2, -1),
('Transgender female', '', 7, 2, -1),
('Transgender male', '', 6, 2, -1),
('Transgender man', '', 6, 2, -1),
('Transgender person', '', NULL, 2, -1),
('Transgender woman', '', 7, 2, -1),
('Transfeminine', '', 7, 2, -1),
('Transmasculine', '', 6, 2, -1),
('Non-binary transgender', '', NULL, 2, -1),
('Transsexual female', '', 9, 3, -1),
('Transsexual male', '', 8, 3, -1),
('Transsexual man', '', 8, 3, -1),
('Transsexual person', '', NULL, 3, -1),
('Transsexual woman', '', 9, 3, -1),
('Non-Binary - other', 'non-binary can be defined as "does not subscribe to the gender binary but identifies with neither, both, or beyond male and female". The term may be used as "an umbrella term, encompassing several gender identities, including intergender, agender, xenogender, genderfluid, and demigender." Some non-binary identities are inclusive, because two or more genders are referenced, such as androgyne/androgynous, intergender, bigender, trigender, polygender, and pangender.: 101  Some non-binary identities are exclusive, because no gender is referenced, such as agender, genderless, neutrois, and xenogender.', NULL, 4, -1),
('Kathoey', '', 7, 2, -1),
('Waria', '', 7, 2, -1),
('Hijra', '', 7, 2, -1),
('Travesti', '', 7, 2, -1),
('Third gender', '', 7, 2, -1),
('Queer', '', NULL, 4, -1),
('Abimegender', 'Associated with being profound, deep, and infinite. The term abimegender may be used alone or in combination with other genders.', NULL, NULL, -1),
('Abinary', '', NULL, NULL, -1),
('Adamas gender', 'A gender that is indefinable or indomitable. People identifying with this gender refuse to be categorized in any particular gender identity.', NULL, NULL, -1),
('Aerogender', 'Also called evaisgender, this gender identity changes according to one’s surroundings.', NULL, NULL, -1),
('Aesthetigender', 'Also called aesthetgender, it is a type of gender identity derived from aesthetics.', NULL, NULL, -1),
('Affectugender', 'This is based on the person’s mood swings or fluctuations.', NULL, NULL, -1),
('Agender', 'A person who does not identify themselves with or experience any gender. Agender people are also called null-gender, genderless, gendervoid, or neutral gender.', NULL, 0, -1),
('Agenderfluid', '', NULL, 0, -1),
('Agenderflux', 'A person with this gender identity is mostly agender with brief shifts of belonging to other gender types.', NULL, 0, -1),
('Genderblank', '', NULL, 0, -1),
('Genderfree', '', NULL, 0, -1),
('Polyagender', '', NULL, 0, -1),
('Alexigender', 'The person has a fluid gender identity between more than one type of gender although they cannot name the genders they feel fluid in.', NULL, NULL, -1),
('Aliusgender', 'This gender identity stands apart from existing social gender constructs. It means having a strong specific gender identity that is neither male nor female.', NULL, NULL, -1),
('Amaregender', 'Having a gender identity that changes depending on the person one is emotionally attached to.', NULL, NULL, -1),
('Ambigender', 'Having two specific gender identities simultaneously without any fluidity or fluctuations.', NULL, NULL, -1),
('Ambonec', 'The person identifies themselves as both man and woman and yet does not belong to either.', NULL, NULL, -1),
('Amicagender', 'A gender-fluid identity where a person changes their gender depending on the friends they have.', NULL, NULL, -1),
('Androgyne', 'A person feels a combination of feminine and masculine genders.', NULL, NULL, -1),
('Androgynous', '', NULL, NULL, -1),
('Anesigender', 'The person feels close to a specific type of gender despite being more comfortable in closely identifying themselves with another gender.', NULL, NULL, -1),
('Angenital', 'The person desires to be without any primary sexual characteristics although they do not identify themselves as genderless.', NULL, NULL, -1),
('Anogender', 'The gender identity fades in and out in intensity but always comes back to the same gendered feeling.', NULL, NULL, -1),
('Anongender', 'The person has a gender identity but does not label it or would prefer to not have a label.', NULL, NULL, -1),
('Antegender', 'A protean gender that can be anything but is formless and motionless.', NULL, NULL, -1),
('Anxiegender', 'This gender identity has anxiety as its prominent characteristic.', NULL, NULL, -1),
('Apagender', 'The person has apathy or a lack of feelings toward ones gender identity.', NULL, NULL, -1),
('Apconsugender', 'It means knowing what are not the characteristics of gender but not knowing what are its characteristics. Thus, a person hides its primary characteristics from the individual.', NULL, NULL, -1),
('Aporagender', '', NULL, NULL, -1),
('Astergender', 'The person has a bright and celestial gender identity.', NULL, NULL, -1),
('Astral gender', 'Having a gender identity that feels to be related to space.', NULL, NULL, -1),
('Autigender', 'Having a gender identity that feels to be closely related to being autistic.', NULL, NULL, -1),
('Autogender', 'Having a gender experience that is deeply connected and personal to oneself.', NULL, NULL, -1),
('Axigender', 'A gender identity that is between the two extremes of agender and any other type of gender. Both the genders are experienced one at a time without any overlapping. The two genders are described as on the opposite ends of an axis.', NULL, NULL, -1),
('Bakla', '', NULL, NULL, -1),
('Bigender', 'Having two gender identities at the same or different times.', NULL, NULL, -1),
('Biogender', 'Having a gender that is closely related to nature.', NULL, NULL, -1),
('Bissu', '', NULL, NULL, -1),
('Blurgender', 'Also called gender fuss, blurgender means having more than one gender identities that blur into each other so that no particular type of gender identity is clear.', NULL, NULL, -1),
('Boyflux', 'The person identifies themselves as male, but they experience varying degrees of male identity. This may range from feeling agender to completely male.', NULL, NULL, -1),
('Burstgender', 'Frequent bursts of intense feelings quickly move to the initial calm stage.', NULL, NULL, -1),
('Butch', '', NULL, NULL, -1),
('Caelgender', 'This gender identity shares the qualities or aesthetics of outer space.', NULL, NULL, -1),
('Calabai', '', NULL, NULL, -1),
('Calalai', '', NULL, NULL, -1),
('Cassgender', 'It is associated with the feelings of considering the gender irrelevant or unimportant.', NULL, NULL, -1),
('Cassflux', 'There is a fluctuating intensity of irrelevance toward gender.', NULL, NULL, -1),
('Cavusgender', 'The person feels close to one gender when depressed and to another when not depressed.', NULL, NULL, -1),
('Cendgender', 'The gender identity changes from one gender to its opposite.', NULL, NULL, -1),
('Ceterogender', 'It is a nonbinary gender where the person has a specific masculine, feminine or neutral feelings.', NULL, NULL, -1),
('Ceterofluid', 'Although the person is a ceterogender, their identity keeps fluctuating between different genders.', NULL, NULL, -1),
('Cloudgender', 'The person’s gender cannot be comprehended or understood due to depersonalization and derealization disorder.', NULL, NULL, -1),
('Collgender', 'Various genders are present at the same time in the individual.', NULL, NULL, -1),
('Colorgender', 'In this category, colors are used to describe gender, for example, pink gender or black gender.', NULL, NULL, -1),
('Commogender', 'The person knows that they are not cisgender yet continues to identify as one for a while.', NULL, NULL, -1),
('Condigender', 'The person feels their gender only under specific circumstances.', NULL, NULL, -1),
('Deliciagender', 'Associated with the feeling of having multiple genders but preferring one over the other.', NULL, NULL, -1),
('Demi-boy', '', NULL, NULL, -1),
('Demifluid', 'Having multiple genders, some fluid while others are static.', NULL, NULL, -1),
('Demiflux', 'A combination of multiple genders with some genders static, whereas others fluctuating in intensity.', NULL, NULL, -1),
('Demigender', 'The individual has partial traits of one gender and the rest of the other gender.', NULL, NULL, -1),
('Demi-girl', '', NULL, NULL, -1),
('Demi-guy', '', NULL, NULL, -1),
('Demi-man', '', NULL, NULL, -1),
('Demi-woman', '', NULL, NULL, -1),
('Domgender', 'The individual has multiple genders with one dominating over the rest.', NULL, NULL, -1),
('Dual gender', '', NULL, NULL, -1),
('Duragender', 'Having more than one gender with one lasting longer than the others.', NULL, NULL, -1),
('Egogender', 'It is a personal type of gender identified by the individual alone. It is based on the person’s experience within the self.', NULL, NULL, -1),
('Epicene', 'It is associated with a strong feeling of not being able to relate to any of the two genders of the binary gender or both of the binary gender characteristics.', NULL, NULL, -1),
('Esspigender', 'The individual relates their gender identity with spirits.', NULL, NULL, -1),
('Eunuch', '', NULL, NULL, -1),
('Exgender', 'The denial to identify with any gender on the gender spectrum.', NULL, NULL, -1),
('Existigender', 'The person’s gender identity exists only when they make conscious efforts to realize it.', NULL, NULL, -1),
('Faʻafafine', '', NULL, NULL, -1),
('Female to male', '', 6, NULL, -1),
('Femfluid', 'The person is fluid or fluctuating regarding the feminine genders.', NULL, NULL, -1),
('Femgender', 'A nonbinary gender identity that is feminine.', NULL, NULL, -1),
('Femme', '', NULL, NULL, -1),
('Fluidflux', 'It means to be fluid between two or more genders with a fluctuation in the intensity of those genders.', NULL, NULL, -1),
('FTM', '', NULL, NULL, -1),
('Gemigender', 'The person has two genders that are opposite yet they flux and work together.', NULL, NULL, -1),
('Gender bender', '', NULL, NULL, -1),
('Gender diverse', '', NULL, NULL, -1),
('Gender gifted', '', NULL, NULL, -1),
('Genderblank', 'It is closely related to a blank space.', NULL, NULL, -1),
('Genderfae', '', NULL, NULL, -1),
('Genderflow', 'The gender identity is fluid between infinite feelings.', NULL, NULL, -1),
('Genderfluid', 'The person does not consistently adhere to one fixed gender and may have many genders.', NULL, NULL, -1),
('Genderflux', 'The gender fluctuates in intensity.', NULL, NULL, -1),
('Genderfuck', 'The person resists to fit in societal norms concerning genders.', NULL, NULL, -1),
('Genderfuzz', 'More than one gender is blurred together.', NULL, NULL, -1),
('Genderless', '', NULL, NULL, -1),
('Gender nonconforming', '', NULL, NULL, -1),
('Genderqueer', 'The individual blurs the preconceived boundaries of gender in relation to the gender binary or having just one gender type.', NULL, NULL, -1),
('Gender questioning', '', NULL, NULL, -1),
('Gender variant', '', NULL, NULL, -1),
('Gender witched', 'The person is inclined toward the notion of having one gender but does not know which.', NULL, NULL, -1),
('Girlflux', 'The individual identifies themselves as a female but with varying intensities of female identities.', NULL, NULL, -1),
('Graygender', '', NULL, NULL, -1),
('Healgender', 'A gender identity that gives the person peace, calm, and positivity.', NULL, NULL, -1),
('Intergender', '', NULL, NULL, -1),
('Ipsogender', '', NULL, NULL, -1),
('Māhū', '', NULL, NULL, -1),
('Male to female', '', 7, NULL, -1),
('Man of trans experience', '', 6, NULL, -1),
('Maverique', '', NULL, NULL, -1),
('Meta-gender', '', NULL, NULL, -1),
('Mirrorgender', '', NULL, NULL, -1),
('MTF', '', NULL, NULL, -1),
('Multigender', '', NULL, NULL, -1),
('Muxe', '', NULL, NULL, -1),
('Neither', '', NULL, NULL, -1),
('Neurogender', '', NULL, NULL, -1),
('Neutrois', '', NULL, NULL, -1),
('Omnigender', 'Having or experiencing all genders.', NULL, NULL, -1),
('Pangender', '', NULL, NULL, -1),
('Person of transgendered experience', '', NULL, NULL, -1),
('Polygender', '', NULL, NULL, -1),
('Sekhet', '', NULL, NULL, -1),
('Trigender', '', NULL, NULL, -1),
('Tumtum', '', NULL, NULL, -1),
('Two spirit', '', NULL, NULL, -1),
('Vakasalewalewa', '', NULL, NULL, -1),
('Winkte', '', NULL, NULL, -1),
('Woman of trans experience', '', 7, NULL, -1),
('X-gender', '', NULL, NULL, -1),
('X-jendā', '', NULL, NULL, -1),
('Xenogender', 'Xenogender can be defined as a gender identity that references "ideas and identities outside of gender". This may include descriptions of gender identity in terms of "their first name or as a real or imaginary animal" or "texture, size, shape, light, sound, or other sensory characteristics".', NULL, NULL, -1);

